# Generated by Django 6.0.5 on 2026-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('driver', 'Driver'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
